INCLUDE (FindPackageHandleStandardArgs)

SET (_INC_SEARCH_PATH)
LIST (APPEND _INC_SEARCH_PATH "/usr/local/neuware/include")
LIST (APPEND _INC_SEARCH_PATH $ENV{CNTOOLKIT_ROOT}/include)

SET (_LIB_SEARCH_PATH)
LIST (APPEND _LIB_SEARCH_PATH "/usr/local/neuware/lib64")
LIST (APPEND _LIB_SEARCH_PATH $ENV{CNTOOLKIT_ROOT}/lib64)

# find cnrt.h
FIND_PATH (CNRT_INCLUDE_DIR cnrt.h PATHS ${_INC_SEARCH_PATH} DOC "location of cnrt.h" NO_DEFAULT_PATH)

# find libcnrt.so
FIND_PATH (CNRT_LIBRARY_DIR libcnrt.so PATHS ${_LIB_SEARCH_PATH} DOC "location of libcnrt.so" NO_DEFAULT_PATH)

# link cnrt
SET(CNRT_LIBRARY cnrt)

# make args
FIND_PACKAGE_HANDLE_STANDARD_ARGS (
    CNRT
    FOUND_VAR
        CNRT_FOUND
    REQUIRED_VARS
        CNRT_INCLUDE_DIR
        CNRT_LIBRARY_DIR
        CNRT_LIBRARY
)

MARK_AS_ADVANCED (
    CNRT_INCLUDE_DIR
    CNRT_LIBRARY
    CNRT_LIBRARY_DIR
)

IF (CNRT_FOUND AND NOT TARGET CNRT::CNRT)
    ADD_LIBRARY (CNRT::CNRT INTERFACE IMPORTED)
    SET_TARGET_PROPERTIES (CNRT::CNRT PROPERTIES INTERFACE_LINK_LIBRARIES   ${CNRT_LIBRARY})
    SET_TARGET_PROPERTIES (CNRT::CNRT PROPERTIES INTERFACE_LINK_DIRECTORIES ${CNRT_LIBRARY_DIR})
    SET_TARGET_PROPERTIES (CNRT::CNRT PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${CNRT_INCLUDE_DIR})
ENDIF()
